"""
Type stub to remove the implicit df argument of @dfpipe functions
so that static type checkers are happy.
"""

def sorter(a): ...
def pivot_table(**kwargs): ...
def reset_index(**kwargs): ...
def sort_values(**kwargs): ...
def to_csv(path, **kwargs): ...
def display(): ...
def agg(list): ...
def replace(*args, **kwargs): ...
def iloc(*args): ...
